### DISCUSSION TITLE
Does it support passwords?

### DISCUSSION THREAD

**Discussion by catdogmaus** [voed/esphome_prana_ble#39] [Q&A]
At least I did not notice about that any information. Device without any password in todays word is historical rarity.
thanks

**Comment by voed** [comment]
Hi. No, current implementation does not support password protected devices. Did not tried to set the password because i am not sure if it can be removed after it. But if can - there's no much sense in a password as esp32 "holds" connection with the recuperator and other devices just cannot connect.

**Reply by catdogmaus** [reply]
I am not sure how passwords with BL are managed but reason I asked is my device has password and actually I don't have seen any device without it - for me that means that I cannot connect to it without password, not that other devices somehow steal the connection. I am surprised that there are devices without it. As far I know default to Prana device is 0000

**Reply by voed** [reply]
My recuperator is like 10 years old and it does not have a password. I can try to make some research, but without owning a password protected device it will be hard to implement that.

**Reply by catdogmaus** [reply]
Yeah that probably wont go just with guesswork. It will sadly cut off all those users with password devices.

**Reply by voed** [reply]
Few years ago i heard somewhere that manufacturer said they will create own home assistant integration. Maybe it worth to remind them:)

**Reply by voed** [reply]
@catdogmaus i did some research and actually, you can try with 0000 pin. If it does not work 'as is', you can try to set passkey:
```
ble_client:
  - mac_address: ${mac_address_01}
    id: prana
    on_passkey_request:
      then:
        - ble_client.passkey_reply:
            id: prana
            passkey: 123456 #or 0000 in your case
```
Cannot guarantee it will work because maybe they made some custom encryption instead of passkey, but it worth to try i guess.
