### ISSUE TITLE
Entities not shown in HA

### ISSUE THREAD

**Issue by okruts** [voed/esphome_prana_ble#1]
I followed your example, new device was discovered but no entities are shown in Home Assistant except firmware. Previously I tried hassio-prana integration and was able to connect using Bluetooth Proxy. Can you please guide me what I'm doing wrong? . Here is my yaml:

```
esphome:
  name: prana
  friendly_name: prana

# Strongly recommended to use IDF framework instead of arduino.
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "MY_ENCRYPTION_KEY"

ota:
  - platform: esphome
    password: "OTA_PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Prana Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# MAC address can be obtained via "BLE Scanner app on your smartphone or BLE Client Tracker component"
# TODO: try to merge it with "prana_ble"
ble_client:
  - mac_address: MY_PRANA_BLE_MAC_ADDRESS
    id: prana

prana_ble:
  id: prana_client
  ble_client_id: prana

# voltage and frequency sensors should be accessible for all models
sensor:
  - platform: prana_ble
    prana_ble_id: prana_client
    voltage:
      name: "Prana voltage"
    frequency:
      name: "Prana frequency"

switch:
# Switch to turn off BLE connection. Useful if you want to connect from native smartphone app
  - platform: prana_ble
    prana_ble_id: prana_client
    connect:
      name: prana_connect
      restore_mode: ALWAYS_ON
    enable:
      id: enable
      name: prana_enable
    heating:
      id: heating
      name: prana_heating
    winter_mode:
      name: prana_winter_mode

# TODO: make option to control in/out fans
fan:
  - platform: prana_ble
    prana_ble_id: prana_client
    name: prana_fan

external_components:
  - source: github://voed/esphome_prana_ble
    components: [prana_ble]
```
