### ISSUE TITLE
requests frequency

### ISSUE THREAD

**Issue by mario-tux** [voed/esphome_prana_ble#16]
As long as I understand, it is the ESP32 that requests an update on the VMC unit, right? 
If this is true, is would be nice to include a way (an `update_interval` in some place) to tune the requests frequency. A too high frequency could pollute frequencies used by bluetooth and the 2.4GHz WiFi. This could make available the ESP32 CPU unit for other tasks.

Thanks.

**Comment by voed** [comment]
It is possible now to do that:
```
prana_ble:
  - id: prana_client
    ble_client_id: prana
    update_interval: 10s
```
