### ISSUE TITLE
support for display content switching

### ISSUE THREAD

**Issue by mario-tux** [voed/esphome_prana_ble#17]
My recent Prana units can switch on the display content (fan speeds, temperature, clock,...) by using the bluetooth remote and the WiFi connection. What do you need to support this kind of functionality? Can I help?

**Comment by voed** [comment]
Hi. I can add buttons to switch the display content, but i am not sure if there are any way to determine which content it currently showing, so you can select exactly what you want instead of just cycling between them. 
To find that out, change log level to `VERBOSE`

Add this buttons to your config so you will be able to switch between displays
```
button:
    - platform: template
      name: prana display left
      on_press:
        then:
            - ble_client.ble_write:
                id: prana # your ble_client id
                service_uuid: 0000baba-0000-1000-8000-00805f9b34fb
                characteristic_uuid: 0000cccc-0000-1000-8000-00805f9b34fb
                value: [0xbe, 0xef, 0x04, 0x19] 

    - platform: template
      name: prana display right
      on_press:
        then:
            - ble_client.ble_write:
                id: prana # your ble_client id
                service_uuid: 0000baba-0000-1000-8000-00805f9b34fb
                characteristic_uuid: 0000cccc-0000-1000-8000-00805f9b34fb
                value: [0xbe, 0xef, 0x04, 0x1A] 
```
Then provide packet log(see https://github.com/voed/esphome_prana_ble/issues/1#issuecomment-2271360261 for details) for every display and i will check if there are any useful data.

**Comment by mario-tux** [comment]
I configured the to display buttons and they work well. Then I switched on the verbose logging to track the content of the received packets. I' hope they allow to create a sensor to feedback the display content. A derived control to select one of the available option (without multiple push of right/left button) would be fantastic. 

The log is available at: https://pastebin.com/S2xbCj2d
During this session I started with a "Date" content (the first in the app) and I cycled among all the options:
  Date -> Time  -> Fan -> Temperature inside -> Temperature outside -> CO2 -> VOC -> Humidity -> Pressure -> Date

**Comment by voed** [comment]
Use `display` branch:

```
external_components:
  - source: "https://github.com/voed/esphome_prana_ble@display"
    components: [prana_ble] 
    refresh: 0s
```
Add select to your config:
```
select:
  - platform: prana_ble
    prana_ble_id: prana_client
    name: "Display mode"
```

Then, you will see the select entity in the HA
![image](https://github.com/user-attachments/assets/0cd32d4c-f0ab-417f-adbf-0e8a04e2aed8)
Use left/right buttons like in previous post and if select result changes, describe which number corresponds to the display, like 0 - date, 1 - time, etc
