### ISSUE TITLE
Ability to connect 1+ devices

### ISSUE THREAD

**Issue by Trteich** [voed/esphome_prana_ble#2]
Hi, thank you very much for your work, it is exactly what I was searching for.
Is there ability to connect more than 1 prana recuperator? If yes, how config file should look like?

**Comment by Trteich** [comment]
I've already dealed with it. Works perfect. As mentioned on ESPHome web site, esp32 can serve up to 3 devices without issues

**Comment by voed** [comment]
Ok, try it:
``` yaml

ble_client:
  - mac_address: 00:A0:50:00:00:03
    id: prana
  - mac_address: FF:FF:FF:FF:FF:FF
    id: prana2

prana_ble:
  - id: prana_client
    ble_client_id: prana

  - id: prana_client2
    ble_client_id: prana2

sensor:
  - platform: prana_ble
    prana_ble_id: prana_client
    voltage:
      name: "Prana voltage"
    frequency:
      name: "Prana frequency"

  - platform: prana_ble
    prana_ble_id: prana_client2
    voltage:
      name: "Prana2 voltage"
    frequency:
      name: "Prana2 frequency"
```
