### ISSUE TITLE
wrong unit_of_measurement for pressure: mmHg

### ISSUE THREAD

**Issue by brazoayeye** [voed/esphome_prana_ble#20]
in my Hass I recive the pressure in mmHg but it's showing hPa.
The solution is simple, add in the example:

```
    pressure:
      name: "Pressure"
      unit_of_measurement: mmHg
#      unit_of_measurement: hPa
#      filters:
#      - multiply: 1.3332
```
