### ISSUE TITLE
yaml by device

### ISSUE THREAD

**Issue by brazoayeye** [voed/esphome_prana_ble#21]
I found the yaml setup quite confusing if you have to setup multiple pranas. I found much simplier the setup grouped by device as happens in https://github.com/omerfaruk-aran/esphome_samsung_hvac_bus/blob/main/example.yaml, section devices.

Is it possible to setup this yaml in a similar way?

**Comment by voed** [comment]
Just set prana_ble_id for every component, like this:
```

substitutions:
  name: prana
  device_description: "Monitor and control a Parana Recuperator via bluetooth"
  external_components_source: github://voed/prana_ble@master
  mac_address_01: 00:A0:50:00:00:00
  mac_address_02: 00:A0:50:00:00:01

# TODO: try to merge it with "prana_ble"
# TODO: make option to add by device name?
ble_client:
  - mac_address: ${mac_address_01}
    id: prana
#You can use multiple devices by specifying their MACS and ids
  - mac_address: ${mac_address_02}
    id: prana2

prana_ble:
  - id: prana_client
    ble_client_id: prana
  - id: prana_client2
    ble_client_id: prana2


fan:
  - platform: prana_ble
    prana_ble_id: prana_client
    has_auto: true #if your recuperator does not have auto/auto+ options, change this to false
    name: In/Out fans # use fan_lock switch to control separate fans
    fan_type: BOTH

  - platform: prana_ble
    prana_ble_id: prana_client2
    has_auto: true #if your recuperator does not have auto/auto+ options, change this to false
    name: In/Out fans # use fan_lock switch to control separate fans
    fan_type: BOTH
```

But i cannot guarantee it will work correctly because i cannot test or troubleshoot that. There was some reports from other people that multiple recuperators on a single node does not work.
