### ISSUE TITLE
Fix temperature sensors

### ISSUE THREAD

**Issue by okruts** [voed/esphome_prana_ble#6]
Temperature sensor show incorrect values. At least on Prana 150 Eco Life Series.

**Comment by voed** [comment]
Please check now, all 4 sensors should work for you:
``` yaml

sensor:
  - platform: prana_ble
    prana_ble_id: prana_client
    temperature_inside_inlet: # top left sensor in Prana app
      name: "Prana temperature inside inlet" 
    temperature_inside_outlet: # bottom left sensor in Prana app
      name: "Prana temperature inside outlet" 
    temperature_outside_inlet:  # top right sensor in Prana app
      name: "Prana temperature outside inlet"
    temperature_outside_outlet: # bottom right sensor in Prana app
      name: "Prana temperature outside outlet"

```
